apiVersion: v1
kind: Service
metadata:
  name: {{ include "redguard.fullname" . }}-svc
  labels:
    {{- include "redguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "redguard.selectorLabels" . | nindent 4 }}
